# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev237+g8a215d2.d20221018'
__version_tuple__ = version_tuple = (0, 1, 'dev237', 'g8a215d2.d20221018')
